import type { Metadata } from "next";
import "@/style/globals.css";
import Navbar from "@/components/layout/Navbar";
import ReactQueryProvider from "@/lib/ReactQueryProvider"; // ✅ import your provider
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* ✅ Wrap everything inside ReactQueryProvider */}
        <ReactQueryProvider>
          <Navbar />
          {children}
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
